#pragma once

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25

#define MATRIX_ROWS 10
#define MATRIX_COLS 19

#define MAIN_ROWS 10
#define MAIN_COLS 11
#define LEFT_ROWS 6
#define LEFT_COLS 4
#define RIGHT_ROWS 5
#define RIGHT_COLS 4

#define UNICODE_CYCLE_PERSIST false
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_WINCOMPOSE

#define I2C_RECHECK_PERIOD 15000U // in ms

#define SLAVE_I2C_ADDRESS_RIGHT (0x76 << 1)
#define SLAVE_I2C_ADDRESS_LEFT (0x77 << 1)

#undef USE_I2C
#define USE_I2C TRUE
#undef I2C_DRIVER
#define I2C_DRIVER I2CD0
#undef I2C1_SCL_PIN
#define I2C1_SCL_PIN GP5
#undef I2C1_SDA_PIN
#define I2C1_SDA_PIN GP4

#undef F_SCL
#define F_SCL 1000000

#ifdef CONSOLE_ENABLE
#define DEBUG_MATRIX_SCAN_RATE
#endif
